### PR TITLE
Serial timeouts fix

### PR DESCRIPTION
**Pull request by shinhub**
Adapt serial timeouts for GUI to longer one only when needed (long FW commands), now manual timeout in the way has been fixed.
Restore serial timeouts to original GUI ones for all other cases.

### CODE REVIEW

**Comment by shinhub** [comment]
Please hold while fixing DETECTION output

**Comment by iceman1001** [comment]
Work-In-Progress?  Or you want me to merge?  and you make a new PR for detection output?

**Comment by shinhub** [comment]
I hoped for an immediate short fix in this one, as this is related to the way serial results are read now they are fixed, but it may also need FW fix, and work is still in progress on FW side. You can merge this one, and I will do another one for DETECTION GUI use.

**Comment by iceman1001** [comment]
Superb!

**Pull request merged**
