### PR TITLE
Added functionality for RevG

### PR DESCRIPTION
**Pull request by Vrumfondel**
Adapted to latest official Firmware for RevG hardware.
I hoped to keep compatibility with RevE, but don't have hardware to test.

Additional comments:
In the officially released Firmware for RevG the button, logging and LED configs are "global", so one setting is valid for all slots. This can be changed today by setting corresponding compile switch in the chameleon source, and might be configurable in future.

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice!
@bogiton  maybe have time to look how this one looks like.  I don't have RevG to test with.

**Comment by bogiton** [comment]
I also don't have a RevG, only RevE rebooted. 
RevG support is a very positive addition, as long as the functionality of the RevE is not messed with. :)

**Comment by iceman1001** [comment]
No time to test,  but @bogiton do the RevE functionality work still?

**Comment by iceman1001** [comment]
Lets see if this works or not...

**Pull request merged**
