### PR TITLE
Crapto1Sharp package instead of Crapto1.cpp

### PR DESCRIPTION
**Pull request by kgamecarter**
I implement a C# version Crapto1 & mfkey32.
[Crapto1Sharp](https://github.com/kgamecarter/Crapto1Sharp)
so I tried to use Crapto1Sharp package instead of Crapto1.cpp.

And I let mfkey32 able to input more than 2 nonce for increasing success rate.

### CODE REVIEW

**Comment by iceman1001** [comment]
Cool that you did a C# implementation.  Thats fine and good.
I am curious about what new function do you add with this PR?

**Comment by kgamecarter** [comment]
I let MfKeyAttacks.KeyWorker method input many nr,ar to a mfkey32 for increasing success rate.
See https://github.com/iceman1001/ChameleonMini-rebootedGUI/commit/607d304d754351f1d22569986be48fcf2263eeb4

**Comment by iceman1001** [comment]
... ok,  Is your c# implementation faster than the current one?

**Comment by kgamecarter** [comment]
Yes, I use Stopwatch class to Measuring code execution time.
Cpp version takes approximately 2000ms.
C# implementation takes approximately 900ms

But I don't know why faster.
May be I use Array.Sort() of .NET Framework instead of Crapto1.cpp quicksort() implementation.

img

**Comment by kgamecarter** [comment]
I know why faster.
Because I build crapto1.cpp in Debug mode.

I try Release mode. C# implementation slower approximately 10%
img

**Comment by kgamecarter** [comment]
But I use groupby {block,keytype} instead of nested for loop.
It's able to avoid redundancy calculation.

**Comment by kgamecarter** [comment]
I try to Parallel.ForEach() search candidate key.

C# implementation faster approximately 6%

img

**Comment by kgamecarter** [comment]
Parallel attack multiple sector,keyType.
Parallel attack multiple slot.
More parallel, More faster.

**Comment by RfidResearchGroup** [comment]
Now it starts getting interesting...

**Comment by iceman1001** [comment]
I dislike new lib-package idea,  but I do like the effort you spent and would hate to see it got to waste.

**Pull request merged**
